// SPDX-License-Identifier: GPL-3.0
pragma solidity >=0.8.0 <0.9.0;

import {GPv2Order} from "cowprotocol/contracts/libraries/GPv2Order.sol";
import {IERC165} from "safe/interfaces/IERC165.sol";

/// @dev Canonical reason for `PollNeedsOffchainInput`: the handler cannot
///      generate with empty `offchainInput` and has no more specific reason.
///      Handlers MAY declare their own reason errors naming the missing input.
error OffchainInputRequired();

/**
 * @title Conditional Order Interface
 * @author CoW Protocol Developers + mfw78 <mfw78@rndlabs.xyz>
 */
interface IConditionalOrder {
    /// @dev This error is returned by the `generateOrder` function if the order condition is not met.
    ///      `reasonCode` is the selector of a handler-declared custom error, so any ABI-aware
    ///      consumer can resolve it to a name without a bespoke table.
    error OrderNotValid(bytes4 reasonCode);

    // --- errors specific for polling
    // Signal to a monitoring service that polling should be attempted again.
    error PollTryNextBlock(bytes4 reasonCode);
    // Signal to a monitoring service that polling should be attempted again at a specific block number.
    error PollTryAtBlock(uint256 blockNumber, bytes4 reasonCode);
    // Signal to a monitoring service that polling should be attempted again at a specific timestamp.
    error PollTryAtTimestamp(uint256 timestamp, bytes4 reasonCode);
    /// @dev Generation requires non-empty `offchainInput` that the caller did not
    ///      supply. Unlike the timed poll errors, this is not a retry signal:
    ///      consumers MUST NOT re-poll with empty input on a schedule - acquire
    ///      the input (see `docs/discovery.md` on order modules) or park the order.
    error PollNeedsOffchainInput(bytes4 reasonCode);

    /**
     * @dev This struct is used to uniquely identify a conditional order for an owner.
     *      H(handler || salt || staticInput) **MUST** be unique for an owner.
     */
    struct ConditionalOrderParams {
        IConditionalOrder handler;
        bytes32 salt;
        bytes staticInput;
    }

    /**
     * Generate the discrete order for the current conditions.
     * @dev The single source of truth for order derivation, shared by `verify` and
     *      `IConditionalOrderGenerator.poll`. **MUST** revert with one of the
     *      conditional-order errors above if the order condition is not met.
     * @param owner the contract who is the owner of the order
     * @param sender the `msg.sender` of the parent `isValidSignature` call
     * @param ctx the context of the order (bytes32(0) if merkle tree is used, otherwise the H(params))
     * @param staticInput the static input for all discrete orders cut from this conditional order
     * @param offchainInput dynamic off-chain input for a discrete order cut from this conditional order
     * @return the discrete order for submission to the CoW Protocol API
     */
    function generateOrder(
        address owner,
        address sender,
        bytes32 ctx,
        bytes calldata staticInput,
        bytes calldata offchainInput
    ) external view returns (GPv2Order.Data memory);

    /**
     * Verify if a given discrete order is valid.
     * @dev Used in combination with `isValidSafeSignature` to verify that the order is signed by the Safe.
     *      **MUST** revert if the order condition is not met.
     * @dev The `order` parameter is ignored / not validated by the `IConditionalOrderGenerator` implementation.
     *      This parameter is included to allow more granular control over the order verification logic, and to
     *      allow a monitoring service / user to propose a discrete order without it being generated by on-chain logic.
     * @param owner the contract who is the owner of the order
     * @param sender the `msg.sender` of the transaction
     * @param _hash the hash of the order
     * @param domainSeparator the domain separator used to sign the order
     * @param ctx the context key of the order (bytes32(0) if a merkle tree is used, otherwise H(params)) with which to lookup the cabinet
     * @param staticInput the static input for all discrete orders cut from this conditional order
     * @param offchainInput dynamic off-chain input for a discrete order cut from this conditional order
     * @param order `GPv2Order.Data` of a discrete order to be verified (if *not* an `IConditionalOrderGenerator`).
     */
    function verify(
        address owner,
        address sender,
        bytes32 _hash,
        bytes32 domainSeparator,
        bytes32 ctx,
        bytes calldata staticInput,
        bytes calldata offchainInput,
        GPv2Order.Data calldata order
    ) external view;
}

/**
 * @title Conditional Order Generator Interface
 * @author mfw78 <mfw78@rndlabs.xyz>
 * @notice Adds structured, non-reverting polling for monitoring service integration.
 * @dev The generator surface carries the handler's *verdict* only. Observed fill
 *      state is orthogonal and is composed by the registry (`ComposableCoW`),
 *      never by a handler.
 */
interface IConditionalOrderGenerator is IConditionalOrder, IERC165 {
    /**
     * @dev This event is emitted when a new conditional order is created.
     * @param owner the address that has created the conditional order
     * @param params the address / salt / data of the conditional order
     * @param context the resolved cabinet value for context-created orders
     *        (abi-encoded bytes32), empty bytes otherwise
     */
    event ConditionalOrderCreated(
        address indexed owner, IConditionalOrder.ConditionalOrderParams params, bytes context
    );

    /**
     * @dev The handler's verdict on whether a discrete order can be posted.
     *      These are the only values a handler can produce; fill state is
     *      deliberately not representable here.
     */
    enum GeneratorResultCode {
        POST, // A discrete order is ready to be posted
        WAIT_TIMESTAMP, // Wait until `waitUntil` (unix timestamp)
        WAIT_BLOCK, // Wait until `waitUntil` (block number)
        TRY_NEXT_BLOCK, // Transient condition, retry next block
        INVALID, // Permanently invalid, stop polling
        NEEDS_INPUT // Requires non-empty offchainInput; acquire input or park - never a timed retry
    }

    /**
     * @dev Structured result from `poll`.
     * @param code the handler's verdict
     * @param order the discrete order; only valid when `code == POST`
     * @param nextPollTimestamp when to poll for the next discrete order after this
     *        one is posted; only meaningful when `code == POST`. `0` means poll at
     *        `order.validTo + 1`; `type(uint256).max` means this is the final order.
     * @param waitUntil the timestamp (`WAIT_TIMESTAMP`) or block number
     *        (`WAIT_BLOCK`) to wait for; `0` otherwise
     * @param reasonCode selector of the handler-declared error behind a non-POST
     *        verdict; `bytes4(0)` for POST. For a caught `Panic` or `Error(string)`
     *        this is that built-in's selector - use `tryGenerateOrder` to retrieve
     *        the complete revert data
     */
    struct GeneratorResult {
        GeneratorResultCode code;
        GPv2Order.Data order;
        uint256 nextPollTimestamp;
        uint256 waitUntil;
        bytes4 reasonCode;
    }

    /**
     * Poll for a discrete order with scheduling metadata.
     * @dev Called by monitoring services. **MUST NOT** revert for order conditions: the
     *      conditional-order errors raised by `generateOrder` are decoded into the
     *      returned verdict instead.
     * @param owner the contract who is the owner of the order
     * @param sender the `msg.sender` of the poll call
     * @param ctx the context of the order (bytes32(0) if merkle tree is used, otherwise the H(params))
     * @param staticInput the static input for all discrete orders cut from this conditional order
     * @param offchainInput dynamic off-chain input for a discrete order cut from this conditional order
     * @return result structured verdict with the order (if postable) and scheduling hints
     */
    function poll(address owner, address sender, bytes32 ctx, bytes calldata staticInput, bytes calldata offchainInput)
        external
        view
        returns (GeneratorResult memory result);

    /**
     * Probe order generation and return the full revert data on failure.
     * @dev Diagnostic surface for off-chain consumers: unlike `poll`, the complete
     *      ABI-encoded inner error (including `Panic` sub-codes and unrecognized
     *      custom errors with their arguments) is returned as ordinary return
     *      data, avoiding RPC revert-data handling entirely. Never consulted on
     *      the settlement path.
     * @return success whether a discrete order was generated
     * @return order the discrete order (zeroed when `success` is false)
     * @return revertData the complete ABI-encoded revert data (empty when
     *         `success` is true)
     */
    function tryGenerateOrder(
        address owner,
        address sender,
        bytes32 ctx,
        bytes calldata staticInput,
        bytes calldata offchainInput
    ) external view returns (bool success, GPv2Order.Data memory order, bytes memory revertData);

    /**
     * Get the scheduling hint for the next poll after a successful order.
     * @dev Only consulted after `generateOrder` succeeds.
     * @return nextPollTimestamp `0` = poll at `order.validTo + 1`; `type(uint256).max` = stop
     *         polling after this order; any other value = poll at that timestamp
     */
    function getNextPollTimestamp(address owner, bytes32 ctx, bytes calldata staticInput, GPv2Order.Data memory order)
        external
        view
        returns (uint256 nextPollTimestamp);

    /**
     * Get a human-readable description of the discrete order.
     * @dev Off-chain UX only; never consulted during settlement.
     */
    function describeOrder(address owner, bytes32 ctx, bytes calldata staticInput, GPv2Order.Data memory order)
        external
        view
        returns (string memory description);
}
